In [ ]:
---
title: "Assignment 4"
author: "Anthony J. Kulowski"
date: "September 26, 2018"
output:
  html_document:
    df_print: paged
---
##Question 1
```{r, include=TRUE}

f1 <- function(x) {
  x^2+3*x+1
}

f1(4)
```
##Question 2
```{r, include=TRUE}
f2 <- function(x) {
  prod(x)
}
v2 <- c(2,4,1,5)
f2(v2)
```

##Question 3
```{r, include=TRUE}
f3 <- function(v,n) {
  v[is.na(v)] <- n
  return(v)
}

v3 <- c(2, NA, 4)
f3(v3,3)
```

##Question 4
```{r, include=TRUE}
f4 <- function(x) {
  avg <- mean(x, na.rm = TRUE)
  x[is.na(x)] <- avg
  return(x)
}
v4 <- c(7, NA, 3)
f4(v4)
```

##Question 5
```{r, include=TRUE}
f5 <- function(df) {
  varcount <- ncol(df)
  for (i in 1:varcount) {
      if(is.numeric(df[[i]]) == TRUE) {
         df[[i]][is.na(df[[i]])] <- mean(df[[i]], na.rm = TRUE)
      }
  }
  return(df)
}
sample
print("------")
f5(sample)
```


##Question 6
```{r, include=TRUE}
f6 <- function(df, var1) {
    library(ggplot2)
    rt = ggplot(data = df) + geom_bar(mapping = aes(x = df[,var1]))
  return(rt)
}
f6(titanic, 4)

```


##Question 7
```{r, include=TRUE}
f7 <- function(df, var1, var2) {
    library(ggplot2)
    rt = ggplot(data = df) + geom_bar(mapping = aes(x = df[,var1], fill =
      df[,var2]), position = "dodge")
    return(rt)
}
f7(titanic, 4, 1)
```